import type { Category } from '@/types';

export const categories: Category[] = [
  // ─── 기피 기술직 (우선) ───
  {
    id: 'welding',
    name: '용접기능사',
    icon: 'Flame',
    color: '#EF4444',
    description: '조선·제조업 인력난 속 연봉 5,500만~1억. 해외취업 가능',
    academyCount: 5,
  },
  {
    id: 'plumbing',
    name: '배관기능사',
    icon: 'Wrench',
    color: '#8B5CF6',
    description: '건설·플랜트 필수 기술. 일당 18~26만원',
    academyCount: 4,
  },
  {
    id: 'electrician',
    name: '전기기능사',
    icon: 'Zap',
    color: '#3B82F6',
    description: '전기 분야 기초 자격증. 수요 연평균 6.5% 성장',
    academyCount: 5,
  },
  {
    id: 'tiling',
    name: '타일기능사',
    icon: 'LayoutGrid',
    color: '#F59E0B',
    description: '인테리어 수요 폭증. 일당 19~25만원',
    academyCount: 4,
  },
  {
    id: 'wallpaper',
    name: '도배기능사',
    icon: 'Paintbrush',
    color: '#78716C',
    description: '1인 창업 가능. 인테리어 핵심 기술',
    academyCount: 4,
  },
  {
    id: 'hvac',
    name: '에어컨/냉동',
    icon: 'Snowflake',
    color: '#06B6D4',
    description: '냉동기계기능사. 여름 성수기 수입 폭발',
    academyCount: 4,
  },
  {
    id: 'forklift',
    name: '지게차운전',
    icon: 'Truck',
    color: '#6B7280',
    description: '물류·제조업 필수 자격증. 실기 학원 필수',
    academyCount: 5,
  },
  {
    id: 'waterproof',
    name: '방수기능사',
    icon: 'Droplets',
    color: '#0EA5E9',
    description: '노후건물 증가로 수요 급증. 일당 17~23만원',
    academyCount: 4,
  },
  {
    id: 'painting',
    name: '도장기능사',
    icon: 'PaintBucket',
    color: '#D946EF',
    description: '건설·자동차 도장. 일당 16~22만원',
    academyCount: 4,
  },
  // ─── 깨끗한 직종 (추가) ───
  {
    id: 'care-worker',
    name: '요양보호사',
    icon: 'Heart',
    color: '#FF6B6B',
    description: '고령화 시대 필수 자격증. 320시간 교육 이수 후 취득',
    academyCount: 5,
  },
  {
    id: 'beauty-nail',
    name: '미용사/네일',
    icon: 'Sparkles',
    color: '#EC4899',
    description: '뷰티 업계 국가자격증. 실기 학원 필수',
    academyCount: 4,
  },
  {
    id: 'pilates-yoga',
    name: '필라테스/요가',
    icon: 'Dumbbell',
    color: '#10B981',
    description: 'MZ세대 인기 자격증. 지도자 과정',
    academyCount: 5,
  },
];
